# Generated by Django 3.2.9 on 2022-01-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220108_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='chronic_diseases',
            field=models.TextField(blank=True, null=True),
        ),
    ]
