# Generated by Django 3.2.9 on 2021-12-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_doctor_limited_integer_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='limited_integer_field',
            new_name='accepted_analysis_count',
        ),
    ]
