# Generated by Django 3.2.9 on 2021-12-28 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_limited_integer_field_doctor_accepted_analysis_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='accepted_analysis_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
