# Generated by Django 3.2.9 on 2022-01-03 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_pers_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pers_code',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 11.', regex='^.{11}$')]),
        ),
    ]
