# Generated by Django 3.2.9 on 2022-01-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_user_is_superuser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'pers_code')},
        ),
    ]
