# Generated by Django 3.2.9 on 2022-01-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20220105_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='are_chronic_diseases',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('cannot_say', 'cannot say')], default='cannot_say', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_diseases',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_smoking',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('cannot_say', 'cannot say')], default='cannot_say', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='medicaments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='regions',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='uses_alcohol',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('cannot_say', 'cannot say')], default='cannot_say', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='uses_medicaments',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('cannot_say', 'cannot say')], default='cannot_say', max_length=10),
        ),
    ]
