# Generated by Django 3.2.9 on 2022-01-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_patient_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='regions',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
