# Generated by Django 3.2.9 on 2022-01-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_patient_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='uses_medicaments',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('cannot_say', 'cannot say')], default='no', max_length=10),
        ),
    ]
