# Generated by Django 3.2.9 on 2022-01-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_patient_uses_medicaments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='sert_nr',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='are_chronic_diseases',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('cannot_say', 'cannot say')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_smoking',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('cannot_say', 'cannot say')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='regions',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='uses_alcohol',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('cannot_say', 'cannot say')], default='no', max_length=10),
        ),
    ]
