# Generated by Django 3.2.9 on 2021-12-23 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('None', 'none'), ('Uploaded', 'uploaded'), ('Broken', 'broken'), ('Inwork', 'in work')], max_length=20)),
                ('dicom_file', models.FileField(null=True, upload_to='dicoms/dcm')),
                ('file_jpg', models.FileField(null=True, upload_to='dicoms/img')),
                ('sop_class', models.TextField(null=True)),
                ('patient_name', models.TextField(null=True)),
                ('patient_id', models.TextField(null=True)),
                ('modality', models.TextField(null=True)),
                ('study_date', models.TextField(null=True)),
                ('image_size', models.TextField(null=True)),
                ('pixel_spacing_x', models.TextField(null=True)),
                ('pixel_spacing_y', models.TextField(null=True)),
                ('slice_location', models.TextField(null=True)),
                ('sex', models.TextField(null=True)),
                ('textArea', models.TextField(default=' ', max_length=300)),
                ('uploaded_date', models.DateField(auto_now=True)),
                ('study_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
