# Generated by Django 3.2.9 on 2021-12-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicom',
            name='file_jpg',
            field=models.FileField(null=True, upload_to='dicoms/'),
        ),
        migrations.AddField(
            model_name='dicom',
            name='image_size',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dicom',
            name='modality',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dicom',
            name='patient_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dicom',
            name='patient_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dicom',
            name='pixel_spacing_x',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dicom',
            name='pixel_spacing_y',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dicom',
            name='slice_location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dicom',
            name='sop_class',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dicom',
            name='study_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dicom',
            name='dicom_file',
            field=models.FileField(null=True, upload_to='dicoms/'),
        ),
    ]
