# Generated by Django 3.2.9 on 2021-12-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0002_auto_20211220_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicom',
            name='dicom_file',
            field=models.FileField(null=True, upload_to='dicoms/dcm'),
        ),
        migrations.AlterField(
            model_name='dicom',
            name='file_jpg',
            field=models.FileField(null=True, upload_to='dicoms/img'),
        ),
    ]
