# Generated by Django 3.2.9 on 2021-12-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0002_alter_dicom_study_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicom',
            name='status',
            field=models.CharField(choices=[(0, 'None'), (1, 'Uploaded'), (2, 'Broken'), (3, 'In work')], max_length=20),
        ),
    ]
