# Generated by Django 3.2.9 on 2021-12-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0003_auto_20211220_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicom',
            name='textArea',
            field=models.TextField(default=' ', max_length=300),
        ),
    ]
