# Generated by Django 3.2.9 on 2021-12-23 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dicom_viewer', '0003_alter_dicom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicom',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Uploaded', 'Uploaded'), ('Broken', 'Broken'), ('In work', 'In work')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dicom',
            name='study_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
