# Generated by Django 3.2.9 on 2021-12-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0004_dicom_textarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicom',
            name='upladed_date',
            field=models.DateField(auto_now=True),
        ),
    ]
