# Generated by Django 3.2.9 on 2021-12-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0005_dicom_upladed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicom',
            old_name='upladed_date',
            new_name='uploaded_date',
        ),
    ]
