# Generated by Django 3.2.9 on 2021-12-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0006_rename_upladed_date_dicom_uploaded_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicom',
            name='sex',
            field=models.TextField(null=True),
        ),
    ]
