# Generated by Django 3.2.9 on 2021-12-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0006_dicom_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicom',
            name='medical_verdict',
            field=models.TextField(blank=True, null=True),
        ),
    ]
