# Generated by Django 3.2.9 on 2021-12-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0008_dicom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicom',
            name='status',
            field=models.CharField(choices=[('None', 'none'), ('Uploaded', 'uploaded'), ('Broken', 'broken')], default='none', max_length=20),
        ),
    ]
