# Generated by Django 3.2.9 on 2022-01-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0008_alter_dicom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicom',
            name='patient_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dicom',
            name='study_date',
            field=models.TextField(null=True),
        ),
    ]
