# Generated by Django 3.2.9 on 2022-01-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0009_auto_20220103_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicom',
            name='medical_verdict',
            field=models.TextField(null=True),
        ),
    ]
