# Generated by Django 3.2.9 on 2022-01-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_viewer', '0010_alter_dicom_medical_verdict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicom',
            name='slice_location',
        ),
        migrations.RemoveField(
            model_name='dicom',
            name='sop_class',
        ),
        migrations.RemoveField(
            model_name='dicom',
            name='type',
        ),
    ]
