# Generated by Django 3.2.9 on 2022-01-06 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dicom_viewer', '0011_auto_20220106_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicom',
            name='study_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
